**Importing necessary library

In [1]:
# data analysis and wrangling
import pandas as pd
import numpy as np

# visualization
import seaborn as sns
import matplotlib.pyplot as plt

# machine learning
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [2]:
train_df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [3]:
train_df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
train_df.describe()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,42000.000000,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,42000.0,...,42000.000000,42000.000000,42000.000000,42000.00000,42000.000000,42000.000000,42000.0,42000.0,42000.0,42000.0
mean,4.456643,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.219286,0.117095,0.059024,0.02019,0.017238,0.002857,0.0,0.0,0.0,0.0
std,2.887730,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.312890,4.633819,3.274488,1.75987,1.894498,0.414264,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,254.000000,254.000000,253.000000,253.00000,254.000000,62.000000,0.0,0.0,0.0,0.0

In [5]:
train_df = train_df.sort_values(by='label', ascending=True)
train_df.head(20)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
9747,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4103,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27801,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27799,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37354,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27797,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4097,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4095,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27804,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12290,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27774,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27755,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37371,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37374,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27751,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12309,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27750,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27780,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12315,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27805,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
train_df = train_df.drop_duplicates(subset='label',keep='first')
X_train= train_df.drop('label', axis=1)
y_train = train_df['label']
X_test = test_df

In [7]:
svc = SVC()
svc.fit(X_train,y_train)
Y_pred = svc.predict(X_test)
Y_pred.sort()
acc_svc = round(svc.score(X_train,y_train)*100,2)
acc_svc

100.0

In [8]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
Y_predi = knn.predict(X_test)
acc_knn = round(knn.score(X_train,y_train)*100,2)
acc_knn

30.0

In [9]:
test_df.index+=1
test_df['ImageId'] = test_df.index

In [10]:
submission = pd.DataFrame({'ImageId':test_df['ImageId'],
                          'Label':Y_pred})
submission.to_csv('submission.csv', index=False)

In [11]:
sub = pd.read_csv('submission.csv')
sub.head(20)

    ImageId  Label
0         1      0
1         2      0
2         3      0
3         4      0
4         5      0
5         6      0
6         7      0
7         8      0
8         9      0
9        10      0
10       11      0
11       12      0
12       13      0
13       14      0
14       15      0
15       16      0
16       17      0
17       18      0
18       19      0
19       20      0